spring.application.name=connectease

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/connecteasedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12041975
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Open-in-view warning disable (Best practice)
spring.jpa.open-in-view=false
server.port=8081